analyze_jd:
  description: >
    Carefully analyze the provided job description to extract critical information about the role.
    Your goal is to summarize the most important requirements the hiring manager is looking for.
    Break down the description into must-have skills, nice-to-have skills, required experience, and relevant industries.
    
    JD:
    {job_description}

  expected_output: >
    A structured summary including:
    - List of must-have skills and qualifications
    - List of nice-to-have skills
    - Required years of experience
    - Preferred industries or domains

  agent: jd_interpreter

shortlist_resumes:
  description: >
    Based on the extracted job requirements, analyze each resume individually and provide a structured evaluation.
    For each resume, extract the candidate's name and mobile number, then score them on a scale from 1 to 10 based on job fit.
    Generate 2-3 relevant interview questions for each candidate and provide reasoning for the score.
    
    CRITICAL: Format your response as a table with the following exact structure:
    
    | Name | Mobile | Score | Questions for Interview | Reasoning |
    |------|--------|-------|------------------------|-----------|
    | [Full Name] | [Phone Number] | [Score/10] | [2-3 interview questions] | [Brief explanation of score] |
    
    Resumes to analyze:
    {resumes}

  expected_output: >
    A properly formatted table with columns: Name, Mobile, Score, Questions for Interview, Reasoning.
    Each row should contain one candidate's complete information.
    Score should be a number between 1-10.
    Extract actual names and phone numbers from resumes.
    Provide specific interview questions relevant to the job requirements.
    Include clear reasoning for each score based on skills match, experience level, and qualifications.

  agent: resume_analyst